# Site configuration
site_name: My Plotly Blog
site_description: A blog with interactive Plotly visualizations
author: Your Name

# GitHub Pages configuration
github_username: username
repository_name: repo-name
base_url: /repo-name  # For project pages; use "" for user pages

# Navigation - add pages here to include them in the site navigation
nav:
  - title: Home
    url: /
  - title: About
    url: /about.html